### ISSUE TITLE
List container is being repainted each time an album is selected

### ISSUE THREAD

**Issue by leathej1** [opus1269/screensaver#2]
Each time an album is selected, a call is made to https://photoslibrary.googleapis.com/v1/mediaItems:search, and then the list-container is repainted. With a lot of albums, this takes many seconds.

**Comment by opus1269** [comment]
Yes. That is expected behavior. If your used to previous versions of the
extension,  it loaded all the photos for all the albums when you first
displayed the list

So, the initial display of the list should be faster, but you pay the cost
when you select the album.

There are now limits to the number of times the extension can call the API
that interfaces with Google Photos, so I am trying to minimize then

I'm working on getting more quota with the folks at Google. In the mean
time, if you could limit the number of albums and photos you select, I
would appreciate it

Regards,
Mike

**Comment by opus1269** [comment]
working as intended
